import { CalendarDays, Clock3, MapPin, Plus } from 'lucide-react-native';
import * as React from 'react';
import { Alert, Pressable, ScrollView, Text, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';

const plans = [
  ['Dinner at Veronica’s', 'Tonight · 8:30 PM', 'Bandra, Mumbai'],
  ['Workout together', 'Mon, 7 Sep · 7:00 AM', 'Home'],
  ['Movie night', 'Fri, 11 Sep · 9:00 PM', 'PVR Icon'],
];

export default function PlansScreen() {
  return <SafeAreaView className="flex-1 bg-[#F4EFE7]" edges={['top']}><ScrollView showsVerticalScrollIndicator={false} contentContainerStyle={{ paddingBottom: 28 }}><View className="flex-row items-center px-[18px] pb-4 pt-3"><Text className="font-serif text-[31px] text-[#18161B]">Plans</Text><Pressable onPress={() => Alert.alert('New plan', 'Plan creation will be connected next.')} className="ml-auto rounded-full bg-[#DF5B5F] p-2"><Plus size={19} color="#FFFFFF" /></Pressable></View><View className="mx-[18px] mb-4 flex-row rounded-xl bg-[#E5DDD2] p-1"><View className="flex-1 items-center rounded-lg bg-[#DF5B5F] py-2"><Text className="text-[10px] font-semibold text-white">Month</Text></View><View className="flex-1 items-center py-2"><Text className="text-[10px] text-[#716B74]">List</Text></View></View><View className="flex-row items-center justify-between px-[18px] pb-3"><Text className="font-serif text-[22px] text-[#18161B]">September 2026</Text><View className="flex-row gap-4"><Text className="text-lg text-[#716B74]">‹</Text><Text className="text-lg text-[#716B74]">›</Text></View></View><View className="mx-[18px] rounded-2xl bg-[#EEE7DD] p-3"><View className="mb-2 flex-row justify-between">{['S','M','T','W','T','F','S'].map((day, index) => <Text key={`${day}-${index}`} className="w-8 text-center text-[9px] text-[#9B949D]">{day}</Text>)}</View><View className="flex-row flex-wrap">{Array.from({ length: 35 }, (_, index) => <View key={index} className="h-9 w-[14.28%] items-center justify-center"><View className={index === 10 ? 'h-7 w-7 items-center justify-center rounded-full bg-[#DF5B5F]' : ''}><Text className={`text-[10px] ${index === 10 ? 'font-semibold text-white' : 'text-[#18161B]'}`}>{index < 3 ? '' : index - 2}</Text></View></View>)}</View></View><View className="mt-5 border-t border-[#D8D0C6] px-[18px] pt-3"><Text className="mb-3 text-[10px] text-[#716B74]">Today · Sat, 5 Sep</Text>{plans.map(([title, time, location]) => <Pressable key={title} onPress={() => Alert.alert(title, `${time} · ${location}`)} className="flex-row items-center border-b border-[#D8D0C6] py-3"><View className="h-11 w-11 items-center justify-center rounded-xl bg-[#E5DDD2]"><CalendarDays size={18} color="#C84449" /></View><View className="ml-3 flex-1"><Text className="text-[11px] font-semibold text-[#18161B]">{title}</Text><View className="mt-1 flex-row items-center"><Clock3 size={12} color="#716B74" /><Text className="ml-1 text-[9px] text-[#716B74]">{time}</Text></View><View className="mt-1 flex-row items-center"><MapPin size={12} color="#716B74" /><Text className="ml-1 text-[9px] text-[#716B74]">{location}</Text></View></View><Text className="text-xl text-[#716B74]">···</Text></Pressable>)}</View></ScrollView></SafeAreaView>;
}
