import { Bell, ChevronRight, Download, Heart, Moon, ShieldCheck, UserRound } from 'lucide-react-native';
import { Alert, Pressable, ScrollView, Text, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';

const settings = [['Relationship', Heart, 'Meera + Arjun', 'Connected 3 Sep 2026'], ['Your plan', ShieldCheck, 'Youse trial', '11 days left · no card'], ['Appearance', Moon, 'Dark mode', 'Applies to the whole app'], ['Notifications', Bell, 'Daily question', '8:00 PM'], ['Privacy & data', Download, 'Export our data', ''], ['Privacy', ShieldCheck, 'Only you and your partner can see your space', ''] ] as const;

export default function UsScreen() {
  return <SafeAreaView className="flex-1 bg-[#F4EFE7]" edges={['top']}><ScrollView contentContainerStyle={{ paddingBottom: 28 }} showsVerticalScrollIndicator={false}><View className="px-4.5 pb-4 pt-3"><Text className="font-serif text-[31px] text-[#18161B]">Us</Text></View><View className="mx-3 flex-row items-center rounded-2xl bg-[#EEE7DD] p-4"><View className="h-12 w-12 items-center justify-center rounded-full bg-[#F9DAD4]"><UserRound size={22} color="#C84449" /></View><View className="ml-3"><Text className="text-[11px] font-semibold text-[#18161B]">Meera Singh</Text><Text className="mt-1 text-[9px] text-[#716B74]">meera@email.com · IST</Text></View></View><Text className="mx-5 mb-2 mt-5 text-[9px] uppercase tracking-[1px] text-[#716B74]">Your space</Text><View className="mx-3 overflow-hidden rounded-2xl bg-[#EEE7DD]">{settings.map(([section, Icon, title, detail]) => <Pressable key={title} onPress={() => Alert.alert(title, detail || 'This static screen is ready for API integration.')} className="flex-row items-center border-b border-[#D8D0C6] px-4 py-4"><Icon size={18} color="#716B74" /><View className="ml-3 flex-1"><Text className="text-[10px] font-medium text-[#18161B]">{title}</Text>{detail ? <Text className="mt-1 text-[9px] text-[#716B74]">{detail}</Text> : null}</View><ChevronRight size={16} color="#9B949D" /></Pressable>)}</View><Text className="mx-5 mb-2 mt-5 text-[9px] uppercase tracking-[1px] text-[#716B74]">Relationship status</Text><Pressable onPress={() => Alert.alert('Unlink partner', 'This action will be connected later.')} className="mx-3 rounded-full border border-[#D8D0C6] py-3"><Text className="text-center text-[11px] text-[#18161B]">Unlink partner</Text></Pressable></ScrollView></SafeAreaView>;
}
