import { Heart, Image as ImageIcon, Plus } from 'lucide-react-native';
import { Alert, Image, Pressable, ScrollView, Text, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';

const memories = [
  ['Ladakh', '12 Jun 2026', 'https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=700&q=82'],
  ['Goa', '3 Feb 2026', 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=700&q=82'],
  ['Our apartment', '14 Dec 2025', 'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&w=700&q=82'],
  ['Diwali', '1 Nov 2025', 'https://images.unsplash.com/photo-1519225421980-715cb0215aed?auto=format&fit=crop&w=700&q=82'],
];

export default function MemoriesScreen() {
  return <SafeAreaView className="flex-1 bg-[#F4EFE7]" edges={['top']}><ScrollView showsVerticalScrollIndicator={false} contentContainerStyle={{ paddingBottom: 28 }}><View className="flex-row items-center px-[18px] pb-4 pt-3"><Text className="font-serif text-[31px] text-[#18161B]">Memories</Text><Pressable onPress={() => Alert.alert('Add memory', 'Photo upload will be connected next.')} className="ml-auto rounded-full bg-[#DF5B5F] p-2"><Plus size={19} color="#FFFFFF" /></Pressable></View><View className="flex-row gap-2 px-[18px] pb-3">{['All', 'Photos', 'Notes', 'Places'].map((tab, index) => <View key={tab} className={`rounded-lg border px-3 py-2 ${index === 0 ? 'border-[#18161B] bg-[#18161B]' : 'border-[#D8D0C6]'}`}><Text className={`text-[9px] ${index === 0 ? 'text-[#F4EFE7]' : 'text-[#716B74]'}`}>{tab}</Text></View>)}</View><Pressable onPress={() => Alert.alert('On this day', 'First trip to the hills')} className="mx-3 mb-3 flex-row items-center rounded-2xl bg-[#EEE7DD] p-3"><Image source={{ uri: memories[0][2] }} className="h-12 w-12 rounded-xl" /><View className="ml-3"><Text className="text-[10px] font-semibold text-[#18161B]">On this day · 1 year ago</Text><Text className="mt-1 text-[9px] text-[#716B74]">First trip to the hills</Text></View><Text className="ml-auto text-xl text-[#716B74]">›</Text></Pressable><View className="flex-row flex-wrap gap-2 px-2">{memories.map(([title, date, image]) => <Pressable key={title} onPress={() => Alert.alert(title, `${date} · Shared memory`)} className="h-[184px] w-[48.5%] overflow-hidden rounded-xl bg-[#E5DDD2]"><Image source={{ uri: image }} className="h-full w-full" /><View className="absolute inset-x-0 bottom-0 bg-black/55 p-2"><Text className="text-[10px] font-semibold text-white">{title}</Text><Text className="mt-1 text-[8px] text-[#E5DDD2]">{date}</Text></View></Pressable>)}</View><View className="mx-[18px] mt-5 flex-row items-center"><ImageIcon size={15} color="#C84449" /><Text className="ml-2 text-[10px] text-[#716B74]">18 shared moments</Text><Heart size={15} color="#C84449" className="ml-auto" /></View></ScrollView></SafeAreaView>;
}
