import { Router } from "express";
import { requireAuth } from "../../middleware/auth.middleware";
import { validate } from "../../middleware/validate";
import * as controller from "./list.controller";
import { createListItemSchema, createListSchema, listEntityIdSchema, updateListItemSchema } from "./list.schema";
export const listRouter = Router();
listRouter.use(requireAuth);
listRouter.get("/lists", controller.list);
listRouter.post("/lists", validate(createListSchema), controller.create);
listRouter.delete("/lists/:id", validate(listEntityIdSchema), controller.remove);
listRouter.post("/lists/:listId/items", validate(createListItemSchema), controller.createItem);
listRouter.patch("/list-items/:id", validate(updateListItemSchema), controller.updateItem);
listRouter.delete("/list-items/:id", validate(listEntityIdSchema), controller.removeItem);
